from tkinter import *
def hello():
    print(e1.get())
    print(e2.get())
root=Tk()
l1=Label(root,text="username")
l1.grid(row=0)
l2=Label(root,text="password")
l2.grid(row=1)
e1=Entry(root)
e1.grid(row=0,column=1)
e2=Entry(root,show='*')
e2.grid(row=1,column=1)
b1=Button(root,text="submit",command=hello)
b1.grid(row=2,column=1)
